language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev

env:
  global:
  - LINT_CHECK="0" TESTS="0"
  - VERSION="12.0" ODOO_REPO="odoo/odoo"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" PHANTOMJS_VERSION="2.1.1"

install:
  - git clone --depth=1 https://github.com/vauxoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
